### ISSUE TITLE
Read-only access to tree elements should not affect write operations

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/AVLIODB#19]
required for https://github.com/ergoplatform/ergo/issues/191

**Comment by catena2w** [comment]
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at org.bouncycastle.crypto.digests.Blake2bDigest.compress(Unknown Source)
	at org.bouncycastle.crypto.digests.Blake2bDigest.doFinal(Unknown Source)
	at scorex.crypto.hash.Blake2b256Unsafe.hash(Blake2b256Unsafe.scala:26)
	at scorex.crypto.hash.Blake2b256Unsafe.prefixedHash(Blake2b256Unsafe.scala:20)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalNode.computeLabel$(BatchNode.scala:41)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.computeLabel(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.Node.label(BatchNode.scala:16)
	at scorex.crypto.authds.avltree.batch.Node.label$(BatchNode.scala:14)
	at scorex.crypto.authds.avltree.batch.InternalProverNode.label(BatchNode.scala:55)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.digest(AuthenticatedTreeOps.scala:40)
	at scorex.crypto.authds.avltree.batch.AuthenticatedTreeOps.digest$(AuthenticatedTreeOps.scala:33)
	at scorex.crypto.authds.avltree.batch.BatchAVLProver.digest(BatchAVLProver.scala:21)
	at scorex.crypto.authds.avltree.batch.BatchAVLProver.digest(BatchAVLProver.scala:148)
	at scorex.crypto.authds.avltree.batch.PersistentBatchAVLProver.digest(PersistentBatchAVLProver.scala:13)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorageSpecification.$anonfun$parallelReadTest$11(VersionedIODBAVLStorageSpecification.scala:101)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorageSpecification.$anonfun$parallelReadTest$5(VersionedIODBAVLStorageSpecification.scala:96)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorageSpecification.$anonfun$parallelReadTest$5$adapted(VersionedIODBAVLStorageSpecification.scala:86)
	at scorex.crypto.authds.avltree.batch.VersionedIODBAVLStorageSpecification.$anonfun$new$1(VersionedIODBAVLStorageSpecification.scala:307)
```
